version: "3.8"

volumes:
  plex:
    driver_opts:
      type: ext4
      device: /dev/sdb1

services:
  spotdl-bot:
    privileged: true
    restart: always
    container_name: spotdl-bot
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
    volumes:
      - plex:/Plex
